# 서버(맥미니) 전용 zsh 설정 — .zshrc 끝에서 source 된다.

# p10k: 호스트 이름을 빨간 배지로 프롬프트 맨 앞에 항상 표시한다.
# (SSH 여부와 무관하게 표시 — 로컬에서 띄운 tmux 에 SSH 로 attach 하면 SSH_CONNECTION 이 없기 때문)
typeset -g POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=(context ${POWERLEVEL9K_LEFT_PROMPT_ELEMENTS:#context})
typeset -g POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS=(${POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS:#context})
typeset -g POWERLEVEL9K_CONTEXT_{DEFAULT,SUDO,REMOTE,REMOTE_SUDO,ROOT}_FOREGROUND=15
typeset -g POWERLEVEL9K_CONTEXT_{DEFAULT,SUDO,REMOTE,REMOTE_SUDO,ROOT}_BACKGROUND=1
typeset -g POWERLEVEL9K_CONTEXT_{DEFAULT,SUDO,REMOTE,REMOTE_SUDO,ROOT}_CONTENT_EXPANSION='%B%m%b'
typeset -g POWERLEVEL9K_CONTEXT_{DEFAULT,SUDO,REMOTE,REMOTE_SUDO,ROOT}_VISUAL_IDENTIFIER_EXPANSION='󰒋'
